name: DeployPolygon
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm install -g @graphprotocol/graph-cli
      - run: npm run codegen
      - run: graph auth --product hosted-service ${API_KEY}
        env:
          API_KEY: ${{ secrets.GRAPH_API_KEY }}
      - run: graph deploy --product hosted-service  posix4e/human-polygon
